site_name: CONTENEDORES
nav:
    - Home: index.md
    - Tutorial Go: tutoriales/contenedorgo.md
    - Tutorial Bash: tutoriales/contenedorbash.md
theme: material
markdown_extensions:
    - admonition
    - abbr
    - pymdownx.snippets
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.mark
    - attr_list